### ISSUE TITLE
not able to do rename

### ISSUE THREAD

**Issue by kambing86** [hax/js-refactor#10]
no error or response after calling the rename function

**Comment by PhiLhoSoft** [comment]
What do you call "rename function"?
How do you call it?

Note: I had to change the key bindings for refactor:rename, because it was conflicting with the window:reload feature. Perhaps you have a similar problem.

**Comment by github-polymer-user** [comment]
@PhiLhoSoft can you post here a snippet for keybindings fix?

https://atom.io/docs/latest/using-atom-basic-customization#customizing-key-bindings

**Comment by PhiLhoSoft** [comment]
https://gist.github.com/PhiLhoSoft/b61b3e3d13ebd802bb08

In short:

```
'atom-workspace atom-text-editor:not([mini])':
  'alt-shift-r': 'refactor:rename'
```

**Comment by hax** [comment]
pls try the latest version and if any problem just open a new issue. Thanks.
