### ISSUE TITLE
Add property renaming

### ISSUE THREAD

**Issue by PhiLhoSoft** [hax/js-refactor#11]
If I have `foo.bar`, I can rename `foo` but not `bar`. Is it possible to rename the properties of an object?
IIRC, I can do that in Brackets with the "Rename JavaScript Identifier" plugin.

Bonus points: also rename `bar` in `foo['bar']`...
Extra bonus points: rename `bar` in `var foo = { x: 5, bar: 'baz' }`

Just checked: the above mentioned plugin is able to do all these renamings...

**Comment by hax** [comment]
Property renaming is dangerous, because we don't know whether `foo` would be return to the outside. We can only safely do it if static analysis prove that `foo` will never leak to the scope. But static analysis is too hard to me. No plan to implement this feature.
