### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by nerdpad** [hax/js-refactor#12]
Title says it all.

**Comment by sarink** [comment]
Doesn't even work for me anymore in the latest atom (v1.8).

I guess so.

:(

**Comment by EzraLopez** [comment]
🙁
I guess we could bring it back to life? I liked its functionality a lot!

**Comment by hax** [comment]
New version will release soon.

**Comment by exwyezed** [comment]
I can't figure out how to make it working.
I tried to change default keybind and seems it still not working.

It's working for you guys?

ATOM version: **1.8.0**
Refactor version: **0.9.2**
js-refactor version: **0.7.2**
OS: **OS X El Capitan 10.11.5**

**Comment by hax** [comment]
@alfonsomga Could you update to js-refactor 0.7.3? if still have problem, just open a new issue. Thank you.
