### ISSUE TITLE
Can't update to 0.7.0

### ISSUE THREAD

**Issue by mimoriarty** [hax/js-refactor#15]
Got this on Ubuntu LTS 14.04:

npm ERR! git fetch -a origin (https://github.com/hax/debug.git) fatal: unable to access 'https://github.com/hax/debug.git/': Received HTTP code 407 from proxy after CONNECT
npm ERR! Linux 3.16.0-76-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/victorpuebla/.atom/.apm/.apmrc" "--userconfig" "/home/victorpuebla/.atom/.apmrc" "install" "/tmp/d-116529-4695-1n715ns/package.tgz" "--target=0.36.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 128

npm ERR! Command failed: fatal: unable to access 'https://github.com/hax/debug.git/': Received HTTP code 407 from proxy after CONNECT
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-116529-4695-1c7o3l/npm-debug.log

I'm under a proxy but has the proper keys on .apmrc & .npmrc. Moreover I can update other packages without any issues.

I got the same error updating refactor to 0.8.0

**Comment by hax** [comment]
Please try latest versions, if still see same problem, reopen this. Thank you!

**Comment by mimoriarty** [comment]
Worked like a charm!! THX hax.
