### ISSUE TITLE
ctrl-alt-r keybinding resets the workspace

### ISSUE THREAD

**Issue by jmaister** [hax/js-refactor#21]

**Comment by gdusart** [comment]
Same here, and trying to change the key binding pops an error: see https://github.com/atom/settings-view/issues/876

**Comment by rvplauborg** [comment]
I changed the key binding successfully - but it does not actually refactor :S

**Comment by hax** [comment]
Problem of keybindings could goto https://github.com/hax/refactor/issues/22
