### ISSUE TITLE
Does not refactor method name key value format

### ISSUE THREAD

**Issue by Timoteus78** [hax/js-refactor#29]
I'm working with [Sencha EXtjs](https://www.sencha.com/products/extjs/). A common pattern for writing methods on a component is as follows:
`Ext.define('Some.package.ComponentName', {`
   `config1: null,`
   `config2: null,`
   `methodName: function () {`
   `},`
   `anotherMethodName: function () {`
      `this.methodName();`
   `}`
`});`

When my cursor is on 
`methodName:`
I am unable to trigger the refactor.

**Comment by hax** [comment]
duplicated #11
