### ISSUE TITLE
I can not update to v0.6.0

### ISSUE THREAD

**Issue by diegognt** [hax/js-refactor#8]
This is the error:

npm WARN addRemoteGit Error: Command failed: 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:658:15)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:98:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:766:16)
npm WARN addRemoteGit     at Socket.<anonymous> (child_process.js:979:11)
npm WARN addRemoteGit     at Socket.emit (events.js:95:17)
npm WARN addRemoteGit     at Pipe.close (net.js:466:12)
npm WARN addRemoteGit  git+https://github.com/hax/debug.git resetting remote /Users/diegonavarro/.atom/.apm/_git-remotes/https-github-com-hax-debug-git-3c6e5b66 because of error: { [Error: Command failed: ] killed: false, code: 1, signal: null }
npm ERR! Darwin 14.5.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/diegonavarro/.atom/.apm/.apmrc" "--userconfig" "/Users/diegonavarro/.atom/.apmrc" "install" "/private/var/folders/73/60myzhtx6kbbz59bmhssnx580000gn/T/d-115815-757-122xenh/package.tgz" "--target=0.22.0" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! path /Users/diegonavarro/.atom/.apm/_git-remotes/https-github-com-hax-debug-git-3c6e5b66
npm ERR! code ENOTEMPTY
npm ERR! errno 53

npm ERR! ENOTEMPTY, rmdir '/Users/diegonavarro/.atom/.apm/_git-remotes/https-github-com-hax-debug-git-3c6e5b66'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/73/60myzhtx6kbbz59bmhssnx580000gn/T/apm-install-dir-115815-757-khx08b/npm-debug.log

**Comment by diegognt** [comment]
Also I got this error:

npm ERR! git clone --template=/Users/diegonavarro/.atom/.apm/_git-remotes/_templates --mirror https://github.com/hax/debug.git /Users/diegonavarro/.atom/.apm/_git-remotes/https-github-com-hax-debug-git-3c6e5b66: Cloning into bare repository '/Users/diegonavarro/.atom/.apm/_git-remotes/https-github-com-hax-debug-git-3c6e5b66'...
npm ERR! git clone --template=/Users/diegonavarro/.atom/.apm/_git-remotes/_templates --mirror https://github.com/hax/debug.git /Users/diegonavarro/.atom/.apm/_git-remotes/https-github-com-hax-debug-git-3c6e5b66: fatal: 'origin' does not appear to be a git repository
npm ERR! git clone --template=/Users/diegonavarro/.atom/.apm/_git-remotes/_templates --mirror https://github.com/hax/debug.git /Users/diegonavarro/.atom/.apm/_git-remotes/https-github-com-hax-debug-git-3c6e5b66: fatal: Could not read from remote repository.
npm ERR! git clone --template=/Users/diegonavarro/.atom/.apm/_git-remotes/_templates --mirror https://github.com/hax/debug.git /Users/diegonavarro/.atom/.apm/_git-remotes/https-github-com-hax-debug-git-3c6e5b66: 
npm ERR! git clone --template=/Users/diegonavarro/.atom/.apm/_git-remotes/_templates --mirror https://github.com/hax/debug.git /Users/diegonavarro/.atom/.apm/_git-remotes/https-github-com-hax-debug-git-3c6e5b66: Please make sure you have the correct access rights
npm ERR! git clone --template=/Users/diegonavarro/.atom/.apm/_git-remotes/_templates --mirror https://github.com/hax/debug.git /Users/diegonavarro/.atom/.apm/_git-remotes/https-github-com-hax-debug-git-3c6e5b66: and the repository exists.
npm ERR! Darwin 14.5.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/diegonavarro/.atom/.apm/.apmrc" "--userconfig" "/Users/diegonavarro/.atom/.apmrc" "install" "/private/var/folders/73/60myzhtx6kbbz59bmhssnx580000gn/T/d-115815-778-quy9jm/package.tgz" "--target=0.22.0" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 128

npm ERR! Command failed: Cloning into bare repository '/Users/diegonavarro/.atom/.apm/_git-remotes/https-github-com-hax-debug-git-3c6e5b66'...
npm ERR! fatal: 'origin' does not appear to be a git repository
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/73/60myzhtx6kbbz59bmhssnx580000gn/T/apm-install-dir-115815-778-7yblmr/npm-debug.log

**Comment by hax** [comment]
Could you try upgrade to latest version v0.7.0?
